build:
  strategy:
    matrix:
      target:
        - x86_64-unknown-linux-gnu
        - x86_64-pc-windows-gnu
      include:
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-latest
        - target: x86_64-pc-windows-gnu
          os: ubuntu-latest
  runs-on: ${{ matrix.os }}
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: 'nmoinvaz/minizip'
        ref: '2.9.2'
        path: 'build'
